# Generated by Django 4.2.1 on 2023-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='expiry_month',
            new_name='expiration_month',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='expiry_year',
            new_name='expiration_year',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('master', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('unknown', 'Unknown')], default='unknown', editable=False, max_length=20),
        ),
    ]
